server:
  port: 8080
  servlet:
    context-path: /fgo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fgo?serverTimezone=GMT
    username: root
    password: 123456
  freemarker:
    suffix: .html
    request-context-attribute: request

mybatis-plus:
  mapper-locations: classpath*:com/fgo/**/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志